#!/bin/bash

# Sets the kitty font size from the current monitor layout: laptop-only gets one
# ctrl+shift+minus step (2.0) smaller than the docked size.
# Writes the generated include and reloads running kitty instances via SIGUSR1.

DOCKED_SIZE=10.0
LAPTOP_SIZE=8.0
CONF="$HOME/.config/kitty/_fontsize.conf"

if hyprctl monitors -j | jq -e 'any(.[]; .name != "eDP-1")' > /dev/null; then
    SIZE=$DOCKED_SIZE
else
    SIZE=$LAPTOP_SIZE
fi

DESIRED="# Generated by ~/.config/hypr/scripts/terminal-font-size.sh — DO NOT EDIT.
font_size $SIZE"

if [ -f "$CONF" ] && [ "$(cat "$CONF")" = "$DESIRED" ]; then
    echo "kitty font size already $SIZE"
    exit 0
fi

printf '%s\n' "$DESIRED" > "$CONF"
echo "kitty font size set to $SIZE"

# SIGUSR1 makes kitty re-read its config; drops any per-window font override.
pkill -USR1 -x kitty || true
