#!/usr/bin/env bash
# Render ~/.config/colors/palette.toml into per-tool partials.
# Consumers @import the generated files; do not edit them by hand.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PALETTE="$ROOT/palette.toml"
EWW_OUT="$HOME/.config/eww/bar/_palette.scss"
ROFI_OUT="$HOME/.config/rofi/_palette.rasi"
KITTY_OUT="$HOME/.config/kitty/_palette.conf"
NVIM_OUT="$HOME/.config/nvim/lua/_palette.lua"
FASTFETCH_OUT="$HOME/.config/fastfetch/config.jsonc"
KDE_OUT="$ROOT/_kde.colors"
KDE_SCHEME_NAME="CallOfTheNight"

if [[ ! -f "$PALETTE" ]]; then
  echo "error: $PALETTE not found" >&2
  exit 1
fi

load_section() {
  local section=$1 prefix=$2
  yq -p toml -o json ".$section" "$PALETTE" \
    | jq -r --arg p "$prefix" '
        to_entries[] |
        $p + (.key | gsub("-"; "_") | ascii_upcase) + "=" + (.value | @sh)
      '
}

eval "$(load_section colors   C_)"
eval "$(load_section geometry G_)"

mkdir -p "$(dirname "$EWW_OUT")" "$(dirname "$ROFI_OUT")" "$(dirname "$KITTY_OUT")" "$(dirname "$NVIM_OUT")"

cat > "$EWW_OUT" <<EOF
// Generated by ~/.config/colors/render.sh — DO NOT EDIT.
// Source: ~/.config/colors/palette.toml

\$primary-color:            $C_PRIMARY;
\$secondary-color:          $C_SECONDARY;
\$background-color:         $C_BACKGROUND;
\$hover-color:              $C_HOVER;
\$overlay-background-color: $C_OVERLAY_BACKGROUND;
\$overlay-hover-color:      $C_OVERLAY_HOVER;
\$border-color:             $C_BORDER;
\$accent-color:             $C_ACCENT;
\$urgent-color:             $C_URGENT;
\$fg-color:                 $C_FG;
\$fg-muted-color:           $C_FG_MUTED;
\$border-radius:            $G_RADIUS;
EOF

cat > "$ROFI_OUT" <<EOF
/* Generated by ~/.config/colors/render.sh — DO NOT EDIT.
   Source: ~/.config/colors/palette.toml */

* {
    primary:        $C_PRIMARY;
    secondary:      $C_SECONDARY;
    bg:             $C_BACKGROUND;
    hover:          $C_HOVER;
    overlay-bg:     $C_OVERLAY_BACKGROUND;
    overlay-hover:  $C_OVERLAY_HOVER;
    border-col:     $C_BORDER;
    accent:         $C_ACCENT;
    urgent:         $C_URGENT;
    fg:             $C_FG;
    fg-muted:       $C_FG_MUTED;
}
EOF

cat > "$KITTY_OUT" <<EOF
# Generated by ~/.config/colors/render.sh — DO NOT EDIT.
# Source: ~/.config/colors/palette.toml
# Mirrors Dolphin's Colors:View background (KDE color scheme).

background $C_VIEW_BG
foreground $C_FG
EOF

cat > "$NVIM_OUT" <<EOF
-- Generated by ~/.config/colors/render.sh — DO NOT EDIT.
-- Source: ~/.config/colors/palette.toml
-- Consumed by lua/plugins/dracula.lua to keep nvim's bg in sync with kitty.

return {
  primary    = "$C_PRIMARY",
  secondary  = "$C_SECONDARY",
  background = "$C_BACKGROUND",
  view_bg    = "$C_VIEW_BG",
  border     = "$C_BORDER",
  accent     = "$C_ACCENT",
  urgent     = "$C_URGENT",
  fg         = "$C_FG",
  fg_muted   = "$C_FG_MUTED",
}
EOF

# Fastfetch can't @import a partial like eww/rofi, and randomize_picture.sh
# rewrites config.jsonc on every run, so we sweep palette-bound SGR escapes
# in-place. Targets only `[38;2;R;G;Bm` truecolor sequences — bold/reset
# and named-color SGRs are untouched.
hex_to_sgr_rgb() {
  local hex=${1#\#}
  printf '%d;%d;%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

if [[ -f "$FASTFETCH_OUT" ]]; then
  C_PRIMARY_SGR=$(hex_to_sgr_rgb "$C_PRIMARY")
  sed -i -E \
    "s/\\\\u001b\\[38;2;[0-9]+;[0-9]+;[0-9]+m/\\\\u001b[38;2;${C_PRIMARY_SGR}m/g" \
    "$FASTFETCH_OUT"
fi

# KDE color scheme. Consumed by Dolphin / Konsole / any Qt-KDE app via a
# symlink at ~/.local/share/color-schemes/${KDE_SCHEME_NAME}.colors. KDE
# wants R,G,B triples (no hex, no alpha) so rgba palette entries are dropped.
hex_to_csv_rgb() {
  local hex=${1#\#}
  printf '%d,%d,%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

K_PRIMARY=$(hex_to_csv_rgb    "$C_PRIMARY")
K_SECONDARY=$(hex_to_csv_rgb  "$C_SECONDARY")
K_BACKGROUND=$(hex_to_csv_rgb "$C_BACKGROUND")
K_VIEW_BG=$(hex_to_csv_rgb    "$C_VIEW_BG")
K_ACCENT=$(hex_to_csv_rgb     "$C_ACCENT")
K_URGENT=$(hex_to_csv_rgb     "$C_URGENT")
K_FG=$(hex_to_csv_rgb         "$C_FG")
K_FG_MUTED=$(hex_to_csv_rgb   "$C_FG_MUTED")

emit_color_group() {
  local section=$1 bg=$2 alt=$3
  cat <<EOF

[$section]
BackgroundNormal=$bg
BackgroundAlternate=$alt
ForegroundNormal=$K_FG
ForegroundInactive=$K_FG_MUTED
ForegroundActive=$K_ACCENT
ForegroundLink=$K_ACCENT
ForegroundVisited=$K_PRIMARY
ForegroundNegative=$K_URGENT
ForegroundNeutral=$K_PRIMARY
ForegroundPositive=$K_ACCENT
DecorationFocus=$K_ACCENT
DecorationHover=$K_PRIMARY
EOF
}

{
  cat <<EOF
# Generated by ~/.config/colors/render.sh — DO NOT EDIT.
# Source: ~/.config/colors/palette.toml

[General]
ColorScheme=$KDE_SCHEME_NAME
Name=$KDE_SCHEME_NAME
shadeSortColumn=true
EOF
  emit_color_group "Colors:View"          "$K_VIEW_BG"    "$K_VIEW_BG"
  emit_color_group "Colors:Window"        "$K_BACKGROUND" "$K_SECONDARY"
  emit_color_group "Colors:Button"        "$K_BACKGROUND" "$K_SECONDARY"
  emit_color_group "Colors:Tooltip"       "$K_SECONDARY"  "$K_BACKGROUND"
  emit_color_group "Colors:Complementary" "$K_SECONDARY"  "$K_BACKGROUND"
  emit_color_group "Colors:Header"        "$K_SECONDARY"  "$K_BACKGROUND"
  cat <<EOF

[Colors:Selection]
BackgroundNormal=$K_PRIMARY
BackgroundAlternate=$K_PRIMARY
ForegroundNormal=$K_SECONDARY
ForegroundInactive=$K_SECONDARY
ForegroundActive=$K_SECONDARY
ForegroundLink=$K_ACCENT
ForegroundVisited=$K_BACKGROUND
ForegroundNegative=$K_URGENT
ForegroundNeutral=$K_SECONDARY
ForegroundPositive=$K_SECONDARY
DecorationFocus=$K_ACCENT
DecorationHover=$K_PRIMARY

[WM]
activeBackground=$K_BACKGROUND
activeForeground=$K_FG
inactiveBackground=$K_SECONDARY
inactiveForeground=$K_FG_MUTED
EOF
} > "$KDE_OUT"

# LibreOffice. UI chrome is themed via the kf6 VCL plugin (SAL_USE_VCLPLUGIN
# in hyprland.conf) which picks up the KDE scheme above. This block only
# touches the document-area Application Colors (cell/canvas bg, Calc grid,
# font, links) and the icon symbol style. The xcu is rewritten by LibreOffice
# on exit, so close it before re-running this script.
LO_XCU="$HOME/.config/libreoffice/4/user/registrymodifications.xcu"
LO_SCHEME="COLOR_SCHEME_LIBREOFFICE_AUTOMATIC"
LO_ICON="breeze_dark"

hex_to_lo_int() {
  local hex=${1#\#}
  printf '%d' "$(( 0x${hex:0:2} * 65536 + 0x${hex:2:2} * 256 + 0x${hex:4:2} ))"
}

if [[ -f "$LO_XCU" ]]; then
  if pgrep -x soffice.bin >/dev/null 2>&1; then
    echo "warn: LibreOffice is running — close it before re-running, or these xcu edits will be clobbered on exit." >&2
  fi

  LO_DOC=$(hex_to_lo_int   "$C_VIEW_BG")
  LO_FONT=$(hex_to_lo_int  "$C_FG")
  LO_GRID=$(hex_to_lo_int  "$C_FG_MUTED")
  LO_LINK=$(hex_to_lo_int  "$C_ACCENT")
  LO_VLINK=$(hex_to_lo_int "$C_PRIMARY")

  LO_CS="/org.openoffice.Office.UI/ColorScheme/ColorSchemes/org.openoffice.Office.UI:ColorScheme['${LO_SCHEME}']"

  LO_ITEMS=(
    "/org.openoffice.Office.Common/Misc|SymbolStyle|$LO_ICON"
    "${LO_CS}/DocColor|Color|$LO_DOC"
    "${LO_CS}/FontColor|Color|$LO_FONT"
    "${LO_CS}/CalcGrid|Color|$LO_GRID"
    "${LO_CS}/Links|Color|$LO_LINK"
    "${LO_CS}/LinksVisited|Color|$LO_VLINK"
  )

  LO_TARGETS=$(printf '%s\n' "${LO_ITEMS[@]}" | awk -F'|' '{print $1"|"$2}')
  LO_INJECT=$(printf '%s\n' "${LO_ITEMS[@]}" | awk -F'|' '{
    printf "<item oor:path=\"%s\"><prop oor:name=\"%s\" oor:op=\"fuse\"><value>%s</value></prop></item>\n", $1, $2, $3
  }')

  LO_TMP=$(mktemp)
  awk -v targets="$LO_TARGETS" -v inject="$LO_INJECT" '
    BEGIN {
      n = split(targets, lines, "\n")
      for (i=1; i<=n; i++) if (lines[i] != "") keys[lines[i]] = 1
    }
    {
      p = ""; nm = ""
      if (match($0, /oor:path="[^"]*"/))  p  = substr($0, RSTART+10, RLENGTH-11)
      if (match($0, /oor:name="[^"]*"/))  nm = substr($0, RSTART+10, RLENGTH-11)
      if (p != "" && nm != "" && ((p "|" nm) in keys)) next
      if ($0 ~ /<\/oor:items>/) { print inject; print; next }
      print
    }
  ' "$LO_XCU" > "$LO_TMP"
  mv "$LO_TMP" "$LO_XCU"
fi

echo "Rendered:"
echo "  $EWW_OUT"
echo "  $ROFI_OUT"
echo "  $KITTY_OUT"
echo "  $NVIM_OUT"
echo "  $KDE_OUT"
[[ -f "$FASTFETCH_OUT" ]] && echo "  $FASTFETCH_OUT (in-place SGR sweep)"
[[ -f "$LO_XCU"        ]] && echo "  $LO_XCU (in-place xcu patch)"
