#!/usr/bin/env bash
# Render ~/.config/colors/palette.toml into per-tool partials.
# Consumers @import the generated files; do not edit them by hand.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PALETTE="$ROOT/palette.toml"
EWW_OUT="$HOME/.config/eww/bar/_palette.scss"
ROFI_OUT="$HOME/.config/rofi/_palette.rasi"
FASTFETCH_OUT="$HOME/.config/fastfetch/config.jsonc"

if [[ ! -f "$PALETTE" ]]; then
  echo "error: $PALETTE not found" >&2
  exit 1
fi

load_section() {
  local section=$1 prefix=$2
  yq -p toml -o json ".$section" "$PALETTE" \
    | jq -r --arg p "$prefix" '
        to_entries[] |
        $p + (.key | gsub("-"; "_") | ascii_upcase) + "=" + (.value | @sh)
      '
}

eval "$(load_section colors   C_)"
eval "$(load_section geometry G_)"

mkdir -p "$(dirname "$EWW_OUT")" "$(dirname "$ROFI_OUT")"

cat > "$EWW_OUT" <<EOF
// Generated by ~/.config/colors/render.sh — DO NOT EDIT.
// Source: ~/.config/colors/palette.toml

\$primary-color:            $C_PRIMARY;
\$secondary-color:          $C_SECONDARY;
\$background-color:         $C_BACKGROUND;
\$hover-color:              $C_HOVER;
\$overlay-background-color: $C_OVERLAY_BACKGROUND;
\$overlay-hover-color:      $C_OVERLAY_HOVER;
\$border-color:             $C_BORDER;
\$accent-color:             $C_ACCENT;
\$urgent-color:             $C_URGENT;
\$fg-color:                 $C_FG;
\$fg-muted-color:           $C_FG_MUTED;
\$border-radius:            $G_RADIUS;
EOF

cat > "$ROFI_OUT" <<EOF
/* Generated by ~/.config/colors/render.sh — DO NOT EDIT.
   Source: ~/.config/colors/palette.toml */

* {
    primary:        $C_PRIMARY;
    secondary:      $C_SECONDARY;
    bg:             $C_BACKGROUND;
    hover:          $C_HOVER;
    overlay-bg:     $C_OVERLAY_BACKGROUND;
    overlay-hover:  $C_OVERLAY_HOVER;
    border-col:     $C_BORDER;
    accent:         $C_ACCENT;
    urgent:         $C_URGENT;
    fg:             $C_FG;
    fg-muted:       $C_FG_MUTED;
}
EOF

# Fastfetch can't @import a partial like eww/rofi, and randomize_picture.sh
# rewrites config.jsonc on every run, so we sweep palette-bound SGR escapes
# in-place. Targets only `[38;2;R;G;Bm` truecolor sequences — bold/reset
# and named-color SGRs are untouched.
hex_to_sgr_rgb() {
  local hex=${1#\#}
  printf '%d;%d;%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

if [[ -f "$FASTFETCH_OUT" ]]; then
  C_PRIMARY_SGR=$(hex_to_sgr_rgb "$C_PRIMARY")
  sed -i -E \
    "s/\\\\u001b\\[38;2;[0-9]+;[0-9]+;[0-9]+m/\\\\u001b[38;2;${C_PRIMARY_SGR}m/g" \
    "$FASTFETCH_OUT"
fi

echo "Rendered:"
echo "  $EWW_OUT"
echo "  $ROFI_OUT"
[[ -f "$FASTFETCH_OUT" ]] && echo "  $FASTFETCH_OUT (in-place SGR sweep)"
